name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Cada día a las 00:00 UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: RodrigoSendinoSanz
          outputs: |
            ./output/github-contribution-grid-snake.svg
            ./output/github-contribution-grid-snake-dark.svg

      - name: Commit y push del snake.svg
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "🎯 Actualiza snake graph automáticamente"
          add: "output/*.svg"
